### ISSUE TITLE
Add Change/Forgot Password Feature

### ISSUE THREAD

**Issue by APlitt24235** [csmith1188/Formbar.js#199]
The "Forgot Password" button should send the user to a page where they can change their password, and it will update the database with that new password.

**Comment by QuanHeMa** [comment]
hi can you assign this to me?

**Comment by csmith1188** [comment]
Also change to allow passwords to contain capital letters and basic symbols ( anything in the number row excep * and () ). This can be done by modifying the regular expression in the password element.

Find a way to communicate password requirements to user
