### ISSUE TITLE
Ability to make premade polls

### ISSUE THREAD

**Issue by Ryan24313** [csmith1188/Formbar.js#230]
- This would let teachers make custom polls that can be saved
- teachers can also make it public so all teachers could use the premade poll if they want

Addresses #218 - 9

**Comment by csmith1188** [comment]
Let's tack some premades onto this in this ticket, as well.

1. Done/Ready? (1 answer)
2. True/False (2 answers)
3. TUTD (3 answers)
4. Multiple Choice (4 answers)
