### ISSUE TITLE
Unescaped characters in labels

### ISSUE THREAD

**Issue by csmith1188** [csmith1188/Formbar.js#244]
Unescaped characters such as " or ' will cause an interface error when trying to parse JSON with those characters in it.

For example, adding this phrase to a poll response label:

_I'm not ready_

... will cause a JSON error at _I'm_, because it thinks it's a JS string symbol.

**Comment by Ryan24313** [comment]
I tested this and it seems like JSON stringify and parse already do this

this is the code I tried
```
let test = { text: `"I'm not ready"` }

console.log(test)
test = JSON.stringify(test)
console.log(test)
test = JSON.parse(test)
console.log(test);
```

this was the output
```
{ text: `"I'm not ready"` }
{"text":"\"I'm not ready\""}
{ text: `"I'm not ready"` } 
```

**Comment by csmith1188** [comment]
I tried adding escape characters manually ( \' ) andI still got the error. Try reproducing it by putting "I'm not ready" as a response label and then having a student look at the panel.
