### ISSUE TITLE
Custom Polls Can Add Answers

### ISSUE THREAD

**Issue by APlitt24235** [csmith1188/Formbar.js#286]
Whenever you start a custom poll while another custom poll is running, the answers to the new custom poll get added to the original, instead of overwriting the answers or causing an error to display.

Steps I took to achieve this:
1. Log in to Formbar with a teacher and student account.
2. Go to Polls, and choose a Custom Poll from the Public Polls, Class Polls, or Your Polls menus. (For this example, I chose TUTD from Public Polls).
3. Then, go back to the Poll menu, and choose another poll in the same way you chose the Poll from Step 2 (I chose True/False from the Public Polls menu). 
4. On the student side, you will notice that the answers from both polls are combined, and the question is the second poll's question. (In my case, the question is "True or False", with the answers being "Up", "Wiggle", "Down", "True", and "False".

A way you could fix this and prevent it is by disabling the Custom Polls menus while a poll is running, and enabling them while there is no poll running (whether it be by making the menu disappear or just disabling the buttons).

**Comment by Ryan24313** [comment]
This should also disable it on the server side in socket.io.
