### ISSUE TITLE
Set up formbar

### ISSUE THREAD

**Issue by Ryan24313** [csmith1188/Formbar.js#321]
Set up the Formbar for testing

Known issues so far:

- [x] 1. Client slowing down with many users joining simultaneously
- [x] 2. Some function seems to be running in the background that locks up the teacher panel when many users are joined. Also shows thousands of "Issues" in the console, but I cannot see what they are.
(This is just about html not being formatted correctly mostly in the tags system)
- [x] 3. Submitting a class code does not redirect to that class automatically. Instead it adds the class to the dropdown and doesn't tell the user. This is very confusing for the user.
- [x] 4. Attempting to enter the class while a Guest redirects them to the student page and gives them an error for having insufficient permissions to view that page. Guests should be able to access the Panel to see the Virtualbar, but not submit answers.
Sort by 
- [x] 5. sorting permissions doesn't work
(was using permissions instead of classPermissions)

Other QOL:

- [x] 6. formPix needs to play a sound when a poll answer is given, the Help Button is pressed, or the Bathroom request is pressed.
- [x] 7. formPix should show the number of students who answered polls out of how many
- [x] 8. The teacher panel should count and show how many students are joined

**Comment by csmith1188** [comment]
Known issues so far:

- Some function seems to be running in the background that locks up the teacher panel when many users are joined. Also shows thousands of "Issues" in the console, but I cannot see what they are.
- Submitting a class code does not redirect to that class automatically. Instead it adds the class to the dropdown and doesn't tell the user. This is very confusing for the user.
- Attempting to enter the class while a Guest redirects them to the student page and gives them an error for having insufficient permissions to view that page. Guests should be able to access the Panel to see the Virtualbar, but not submit answers.
- Sort by permissions doesn't work

Other QOL:
- formPix needs to play a sound when a poll answer is given, the Help Button is pressed, or the Bathroom request is pressed.
- formPix should show the number of students who answered polls out of how many
- The teacher panel should count and show how many students are joined
