### ISSUE TITLE
Multiple-Answer Polls

### ISSUE THREAD

**Issue by APlitt24235** [csmith1188/Formbar.js#365]
This feature allows students to select multiple responses in a poll. 

This allows for the teacher to collect varied data specific to each user, or to check if students got all of the answers correct in a question, in the case of multiple answer questions.

**Comment by csmith1188** [comment]
You can simply give each poll a property called "maxanswers" that defaults to 1. (Porbably need a minanswers, too)

If you form the poll answers in an array:
`{ "poll": ["answer1", "answer2", "answer3"] }`

then you can simply grab the first answer for a regular poll and ignore the rest. In a multipoll you simply loop through them and apply existing poll handling code

The difficult part is how do we store the answers in the database? Multiple entries per single multiresponse?
