### ISSUE TITLE
Class Permission Change cpUpdate()

### ISSUE THREAD

**Issue by luke24279** [csmith1188/Formbar.js#412]
The cpUpdate() function in the classPermChange socket.on in the app.js file has been commented out to fix another issue. Keep an eye out for potential bugs created by this change, and see if it is better to keep it commented and fix the new bugs or uncomment it and fix the old issue in a different way.

**Comment by Luminocents** [comment]
I investigated and have observed that whether or not the cpUpdate in the socket.on "classPermChange" in app.js is commented or not nothing changes. The issues I have seen while investigated that I think are supposed to be affected are as follows.


- Does not save tag changes for other users without refreshing regardless if cpUpdate is commented out or not.

- Manager page tags just do nothing and also has different tags than home control panel. Is also unaffected from commenting out cpUpdate.
