### ISSUE TITLE
Better password storage

### ISSUE THREAD

**Issue by ProfBrickz** [csmith1188/Formbar.js#429]
Currently passwords are just encrypted, they should be changed to use slow hashing. Bcrypt is a possible alternative.

[https://www.youtube.com/watch?v=qgpsIBLvrGY](https://www.youtube.com/watch?v=qgpsIBLvrGY)

[https://www.hivesystems.com/blog/are-your-passwords-in-the-green](https://www.hivesystems.com/blog/are-your-passwords-in-the-green)

**Comment by Luminocents** [comment]
Possibly affects:

- API,
- Password Change Requests

**Comment by ProfBrickz** [comment]
It would definitely affect making or changing passwords. Also it might affect the API a bit.
