### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by csmith1188** [csmith1188/Formbar.js#460]
- Use a .env or gitignored settings to store email login credentials
- On boot, if credentials are valid, enable email capability (some people who run formbar don't have an email account)
- When a new account is made:
- - user must provide an email account for database
- - Set the user's "verified" column to 0 in the database
- - Store the user's email
- - if the email capability is enabled, send a verification email with a webtoken.
- - Add a verification endpoint to change their verified column to 1if they provide the valid webtoken
- - Frontend dev use EJS to prerender a verification email
- - Managers can change users to verified in their master list

**Comment by jesse26603** [comment]
Completed in Pull Request #468
