### ISSUE TITLE
OAuth service

### ISSUE THREAD

**Issue by csmith1188** [csmith1188/Formbar.js#55]
Research OAuth2. Create a service in Formbar.js that allows third-party apps to log in with Formbar.js credentials. This way we can make a universal login for all additional apps we develop in class.

**Comment by Eshimmel** [comment]
https://www.oauth.com/oauth2-servers/single-page-apps/

**Comment by Eshimmel** [comment]
https://www.digitalocean.com/community/tutorials/nodejs-jwt-expressjs

**Comment by Eshimmel** [comment]
https://www.bezkoder.com/node-js-express-login-example/

**Comment by Eshimmel** [comment]
https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2
