### ISSUE TITLE
Integrate socket.io

### ISSUE THREAD

**Issue by csmith1188** [csmith1188/Formbar.js#9]
Use socket.io to establish links between the main application and a browser-based chat page with different chat rooms. This way we can establish how we handle websockets in our application.

As you develop conventions for the websocket system, you **must** update the github repo wiki with the conventions you chose and justification as to why.

**Comment by Riley23062** [comment]
I'll be working on this outside of a program but I will be posting progress in a discussion to be made when I have an MVP
